MetaDataFormat = "toml"
baseurl = "http://yukimemi.github.io"
languageCode = "ja"
title = "YUKIMEMI"
theme = "yukimemi"

# pygmentscodefences = true
# pygmentsstyle = "colorful"
# pygmentsoptions = "linenos=table"

[permalinks]
  page = "/:title/"
  about = "/:filename/"


